# Site settings
title: MacaqueNet
subtitle: 
email: ASABEaster2024@gmail.com
description: An animal behaviour conference
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ASABEaster2024.github.io" # the base hostname & protocol for your site
author: ASABEaster2024
lang: en_US

# Social settings
github_url: https://github.com/ASABEaster2024

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
