# Site settings
title: ASABSpring2024
subtitle: 
email: ASABSpring2024@gmail.com
description: An animal behaviour conference
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ASABSpring2024.github.io" # the base hostname & protocol for your site
author: ASABSpring2024
lang: en_US

# Social settings
github_url: https://github.com/ASABSpring2024

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
